--- #YAML:1.0
name:                OpenGL
version:             0.61
abstract:            ~
license:             ~
author:              
    - Bob 'grafman' Free <grafman at graphcomp.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
