package OpenGL::GLUT;

=head1 NAME

OpenGL::GLUT - module encapsulating GLUT functions

=cut

use strict;
use warnings;

use Exporter 'import';
require DynaLoader;

our $VERSION = '0.7003';
our @ISA = qw(DynaLoader);

our @const = qw(
   GLUT_ACCUM
   GLUT_ACTION_CONTINUE_EXECUTION
   GLUT_ACTION_EXIT
   GLUT_ACTION_GLUTMAINLOOP_RETURNS
   GLUT_ACTION_ON_WINDOW_CLOSE
   GLUT_ACTIVE_ALT
   GLUT_ACTIVE_CTRL
   GLUT_ACTIVE_SHIFT
   GLUT_ALPHA
   GLUT_API_VERSION
   GLUT_BITMAP_8_BY_13
   GLUT_BITMAP_9_BY_15
   GLUT_BITMAP_HELVETICA_10
   GLUT_BITMAP_HELVETICA_12
   GLUT_BITMAP_HELVETICA_18
   GLUT_BITMAP_TIMES_ROMAN_10
   GLUT_BITMAP_TIMES_ROMAN_24
   GLUT_BLUE
   GLUT_CURSOR_BOTTOM_LEFT_CORNER
   GLUT_CURSOR_BOTTOM_RIGHT_CORNER
   GLUT_CURSOR_BOTTOM_SIDE
   GLUT_CURSOR_CROSSHAIR
   GLUT_CURSOR_CYCLE
   GLUT_CURSOR_DESTROY
   GLUT_CURSOR_FULL_CROSSHAIR
   GLUT_CURSOR_HELP
   GLUT_CURSOR_INFO
   GLUT_CURSOR_INHERIT
   GLUT_CURSOR_LEFT_ARROW
   GLUT_CURSOR_LEFT_RIGHT
   GLUT_CURSOR_LEFT_SIDE
   GLUT_CURSOR_NONE
   GLUT_CURSOR_RIGHT_ARROW
   GLUT_CURSOR_RIGHT_SIDE
   GLUT_CURSOR_SPRAY
   GLUT_CURSOR_TEXT
   GLUT_CURSOR_TOP_LEFT_CORNER
   GLUT_CURSOR_TOP_RIGHT_CORNER
   GLUT_CURSOR_TOP_SIDE
   GLUT_CURSOR_UP_DOWN
   GLUT_CURSOR_WAIT
   GLUT_DEPTH
   GLUT_DISPLAY_MODE_POSSIBLE
   GLUT_DOUBLE
   GLUT_DOWN
   GLUT_ELAPSED_TIME
   GLUT_ENTERED
   GLUT_FULLY_COVERED
   GLUT_FULLY_RETAINED
   GLUT_GAME_MODE_ACTIVE
   GLUT_GAME_MODE_DISPLAY_CHANGED
   GLUT_GAME_MODE_HEIGHT
   GLUT_GAME_MODE_PIXEL_DEPTH
   GLUT_GAME_MODE_POSSIBLE
   GLUT_GAME_MODE_REFRESH_RATE
   GLUT_GAME_MODE_WIDTH
   GLUT_GREEN
   GLUT_HAS_DIAL_AND_BUTTON_BOX
   GLUT_HAS_KEYBOARD
   GLUT_HAS_MOUSE
   GLUT_HAS_OVERLAY
   GLUT_HAS_SPACEBALL
   GLUT_HAS_TABLET
   GLUT_HIDDEN
   GLUT_INDEX
   GLUT_INIT_DISPLAY_MODE
   GLUT_INIT_STATE
   GLUT_INIT_WINDOW_HEIGHT
   GLUT_INIT_WINDOW_WIDTH
   GLUT_INIT_WINDOW_X
   GLUT_INIT_WINDOW_Y
   GLUT_KEY_DOWN
   GLUT_KEY_END
   GLUT_KEY_F1
   GLUT_KEY_F10
   GLUT_KEY_F11
   GLUT_KEY_F12
   GLUT_KEY_F2
   GLUT_KEY_F3
   GLUT_KEY_F4
   GLUT_KEY_F5
   GLUT_KEY_F6
   GLUT_KEY_F7
   GLUT_KEY_F8
   GLUT_KEY_F9
   GLUT_KEY_HOME
   GLUT_KEY_INSERT
   GLUT_KEY_LEFT
   GLUT_KEY_PAGE_DOWN
   GLUT_KEY_PAGE_UP
   GLUT_KEY_RIGHT
   GLUT_KEY_UP
   GLUT_LAYER_IN_USE
   GLUT_LEFT
   GLUT_LEFT_BUTTON
   GLUT_LUMINANCE
   GLUT_MENU_IN_USE
   GLUT_MENU_NOT_IN_USE
   GLUT_MENU_NUM_ITEMS
   GLUT_MIDDLE_BUTTON
   GLUT_MULTISAMPLE
   GLUT_NORMAL
   GLUT_NORMAL_DAMAGED
   GLUT_NOT_VISIBLE
   GLUT_NUM_BUTTON_BOX_BUTTONS
   GLUT_NUM_DIALS
   GLUT_NUM_MOUSE_BUTTONS
   GLUT_NUM_SPACEBALL_BUTTONS
   GLUT_NUM_TABLET_BUTTONS
   GLUT_OVERLAY
   GLUT_OVERLAY_DAMAGED
   GLUT_OVERLAY_POSSIBLE
   GLUT_PARTIALLY_RETAINED
   GLUT_RED
   GLUT_RGB
   GLUT_RGBA
   GLUT_RIGHT_BUTTON
   GLUT_SCREEN_HEIGHT
   GLUT_SCREEN_HEIGHT_MM
   GLUT_SCREEN_WIDTH
   GLUT_SCREEN_WIDTH_MM
   GLUT_SINGLE
   GLUT_STENCIL
   GLUT_STEREO
   GLUT_STROKE_MONO_ROMAN
   GLUT_STROKE_ROMAN
   GLUT_TRANSPARENT_INDEX
   GLUT_UP
   GLUT_VERSION
   GLUT_VISIBLE
   GLUT_WINDOW_ACCUM_ALPHA_SIZE
   GLUT_WINDOW_ACCUM_BLUE_SIZE
   GLUT_WINDOW_ACCUM_GREEN_SIZE
   GLUT_WINDOW_ACCUM_RED_SIZE
   GLUT_WINDOW_ALPHA_SIZE
   GLUT_WINDOW_BLUE_SIZE
   GLUT_WINDOW_BUFFER_SIZE
   GLUT_WINDOW_COLORMAP_SIZE
   GLUT_WINDOW_CURSOR
   GLUT_WINDOW_DEPTH_SIZE
   GLUT_WINDOW_DOUBLEBUFFER
   GLUT_WINDOW_FORMAT_ID
   GLUT_WINDOW_GREEN_SIZE
   GLUT_WINDOW_HEIGHT
   GLUT_WINDOW_NUM_CHILDREN
   GLUT_WINDOW_NUM_SAMPLES
   GLUT_WINDOW_PARENT
   GLUT_WINDOW_RED_SIZE
   GLUT_WINDOW_RGBA
   GLUT_WINDOW_STENCIL_SIZE
   GLUT_WINDOW_STEREO
   GLUT_WINDOW_WIDTH
   GLUT_WINDOW_X
   GLUT_WINDOW_Y
   GLUT_XLIB_IMPLEMENTATION
);

our @func = qw(
   done_glutInit
   glutAddMenuEntry
   glutAddSubMenu
   glutAttachMenu
   glutBitmapCharacter
   glutBitmapHeight
   glutBitmapLength
   glutBitmapString
   glutBitmapWidth
   glutButtonBoxFunc
   glutChangeToMenuEntry
   glutChangeToSubMenu
   glutCloseFunc
   glutCopyColormap
   glutCreateMenu
   glutCreateSubWindow
   glutCreateWindow
   glutDestroyMenu
   glutDestroyWindow
   glutDetachMenu
   glutDeviceGet
   glutDialsFunc
   glutDisplayFunc
   glutEnterGameMode
   glutEntryFunc
   glutEstablishOverlay
   glutExtensionSupported
   glutForceJoystickFunc
   glutFullScreen
   glutGameModeGet
   glutGameModeString
   glutGet
   glutGetColor
   glutGetMenu
   glutGetModifiers
   glutGetWindow
   glutHideOverlay
   glutHideWindow
   glutIconifyWindow
   glutIdleFunc
   glutIgnoreKeyRepeat
   glutInit
   glutInitDisplayMode
   glutInitDisplayString
   glutInitWindowPosition
   glutInitWindowSize
   glutKeyboardFunc
   glutKeyboardUpFunc
   glutLayerGet
   glutLeaveGameMode
   glutLeaveMainLoop
   glutMainLoop
   glutMainLoopEvent
   glutMenuDestroyFunc
   glutMenuStateFunc
   glutMenuStatusFunc
   glutMotionFunc
   glutMouseFunc
   glutMouseWheelFunc
   glutOverlayDisplayFunc
   glutPassiveMotionFunc
   glutPopWindow
   glutPositionWindow
   glutPostOverlayRedisplay
   glutPostRedisplay
   glutPostWindowOverlayRedisplay
   glutPostWindowRedisplay
   glutPushWindow
   glutRemoveMenuItem
   glutRemoveOverlay
   glutReportErrors
   glutReshapeFunc
   glutReshapeWindow
   glutSetColor
   glutSetCursor
   glutSetIconTitle
   glutSetKeyRepeat
   glutSetMenu
   glutSetOption
   glutSetWindow
   glutSetWindowTitle
   glutShowOverlay
   glutShowWindow
   glutSolidCone
   glutSolidCube
   glutSolidCylinder
   glutSolidDodecahedron
   glutSolidIcosahedron
   glutSolidOctahedron
   glutSolidRhombicDodecahedron
   glutSolidSphere
   glutSolidTeapot
   glutSolidTetrahedron
   glutSolidTorus
   glutSpaceballButtonFunc
   glutSpaceballMotionFunc
   glutSpaceballRotateFunc
   glutSpecialFunc
   glutSpecialUpFunc
   glutStrokeCharacter
   glutStrokeHeight
   glutStrokeLength
   glutStrokeString
   glutStrokeWidth
   glutSwapBuffers
   glutTabletButtonFunc
   glutTabletMotionFunc
   glutTimerFunc
   glutUseLayer
   glutVisibilityFunc
   glutWarpPointer
   glutWindowStatusFunc
   glutWireCone
   glutWireCube
   glutWireCylinder
   glutWireDodecahedron
   glutWireIcosahedron
   glutWireOctahedron
   glutWireRhombicDodecahedron
   glutWireSphere
   glutWireTeapot
   glutWireTetrahedron
   glutWireTorus
);

our @EXPORT_OK = (@const, @func, qw(_have_glut _have_freeglut glpHasGLUT));
our %EXPORT_TAGS = (
  all => \@EXPORT_OK,
  constants => \@const,
  glutconstants => \@const,
  functions => \@func,
  glutfunctions => \@func,
);

__PACKAGE__->bootstrap;

1;
