#!make

CC=cc
GLUT_DEF = NO_GLUT_DEF_GIVEN # harmless to define, but must give something
CCFLAGS= -D$(GLUT_DEF)
LINK=cc
LDFLAGS=-framework OpenGL $(GLUT_LIB)

all: glversion.txt

clean:
	rm -f glversion.txt
	rm -f glversion
	rm -f glversion.o

glversion.txt: glversion
	./$< > $@

glversion: glversion.o
	${LINK} ${LDFLAGS} -o $@ $<
	chmod u+x $@

%.o: %.c
	${CC} -Wno-deprecated-declarations ${CCFLAGS} -c $<
